application: musiqtown
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript
  
- url: /.*
  script: lisn.application
  login: admin
